name: Deploy to Azure (dev)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Install Azure CLI and jq
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt-get install jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zuydspeelt-web-api:latest
          build-args: ZUYDSPEELT_CONNECTIONSTRING=${{ secrets.ZUYDSPEELT_CONNECTIONSTRING_DEV }}

      - name: Login to Azure
        run: |
          az login --service-principal --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT }} --output none

      - name: Enable CD
        id: enable_cd
        run: |
          CI_CD_URL=$(az webapp deployment container config --enable-cd true --name zuydspeeltapi-dev --resource-group B2C6B | jq -r '.CI_CD_URL')
          echo "CI_CD_URL=$CI_CD_URL" >> $GITHUB_ENV

      - name: Deploy Template
        run: |
          az deployment group create --resource-group B2C6B --template-file template-dev.json --parameters parameters-dev.json

      - name: Trigger Azure Deployment
        run: |
          curl -d{} $CI_CD_URL
