name: .NET

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test

    - name: Success Notification
      if: ${{ success() }}
      uses: mikesprague/teams-incoming-webhook-action@v1
      with:
        github-token: ${{ github.token }}
        webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        deploy-card: true
        title: 'Deployment Successful'
        color: 'success'
        
    - name: Failure Notification
      if: ${{ failure() }}
      uses: mikesprague/teams-incoming-webhook-action@v1
      with:
        github-token: ${{ github.token }}
        webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        deploy-card: true
        title: 'Deployment Failed'
        color: 'failure'
    
    - name: Cancelled Notification
      if: ${{ cancelled() }}
      uses: mikesprague/teams-incoming-webhook-action@v1
      with:
        github-token: ${{ github.token }}
        webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        deploy-card: true
        title: 'Deployment Cancelled'
        color: 'warning'
        
    
